#!/bin/bash

setxkbmap -layout us -variant intl -option caps:super,altwin:menu_win &
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
xset -q | grep -q "Caps Lock:\s*on" && xdotool key Caps_Lock

xset r rate 300 50 
xset s off -dpms 
xsetroot -solid "#54487A"

slstatus &
unclutter &
redshift -l -33.45694:-70.64827 -t 5700:2600 &
picom --backend=glx --window-shader-fg=$HOME/.local/share/picom/picom-grayscale-shader.glsl &

